name: Golang CI

on:
  push:
    branches: main
jobs:
  build-golang-artifacts:
    runs-on: ubuntu-latest
    steps:
      - run: echo " hello github actions"
      - name: checkout
        uses: actions/checkout@v4
      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Install dependencies
        run: go mod download
      - name: Verify dependencies
        run: go mod verify
      - name: run tests
        run: go test ./...
      - name: build binary
        run: |
            mkdir myapp
            go build -o myapp
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-binary
          path: myapp
          retention-days: 1
          




